version: '3'

services:
  fedora:
    image: bee2:fedora
    build: 
      context: .
      dockerfile: dockerfiles/rawhide.Dockerfile
    volumes:
      - .:/usr/src

  s390x:
    image: s390x_fedora
    build: 
      context: .
      dockerfile: dockerfiles/s390x.Dockerfile
    volumes:
      - .:/usr/src

  s390x_test:
    image: s390x_fedora
    command: bash "scripts/run_tests.sh"
    volumes:
      - .:/usr/src

  s390:
    image: s390x_debian
    build: 
      context: .
      dockerfile: dockerfiles/s390.Dockerfile
    volumes:
      - .:/usr/src

  s390_test:
    image: s390x_debian
    command: bash "scripts/run_tests.sh"
    volumes:
      - .:/usr/src

  debian:
    image: bee2:debian
    build: 
      context: .
      dockerfile: dockerfiles/rawhide.Dockerfile
    volumes:
      - .:/usr/src  
