# Build and run tests on the baseline platform

name: build

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master", "actions" ]

jobs:
  build:
    name: Build and test
    runs-on: windows-latest
    strategy:
      matrix:
        include:
        - BUILD_TYPE: Release
          BUILD_FAST: OFF
          BASH_PLATFORM: BASH_64
          CC: gcc

    steps:
    - name: Get source
      uses: actions/checkout@v3

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Get CMake
      uses: symbitic/install-cmake@master

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DBUILD_FAST=${{matrix.BUILD_FAST}} -DBASH_PLATFORM=${{matrix.BASH_PLATFORM}} -G "MinGW Makefiles"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.BUILD_TYPE}} --verbose
